### ISSUE TITLE
Memory leak in server.py

### ISSUE THREAD

**Issue by vtlkvl** [Kong/kong-python-pdk#120]
We ran into a memory leak in Kong Plugin Server that can be reproduced as described in https://github.com/vtlkvl/kong-python-pluginserver-memory-leak. We figured out that for each plugin call the messaging queue is added to `PluginServer.events` in [PluginServer.handle_event](https://github.com/Kong/kong-python-pdk/blob/master/kong_pdk/server.py#L305), but `PluginServer._step` and specifically [removal of the queue](https://github.com/Kong/kong-python-pdk/blob/master/kong_pdk/server.py#L341) is done just for the last plugin. So if you have 10 plugins, 10 queues will be added to `PluginServer.events`, but just 1 will be deleted and 9 will remain in the memory and never get GCed. As a result `PluginServer.events` will grow until OOM.

**Comment by vtlkvl** [comment]
@fffonion I've got a fix for the issue. Can I get write access to push a feature branch to make a PR?

**Comment by fffonion** [comment]
@vtlkvl we usually don't grant access to community contributers, please creeate a fork and create PR from there : ) Feel free to ping me when it's ready.

**Comment by vtlkvl** [comment]
@fffonion I've made a [PR](https://github.com/Kong/kong-python-pdk/pull/122). Once it is approved and merged, how long does it take to get a new version?

**Comment by fffonion** [comment]
@vtlkvl I will release a new version once the PR is merged!

**Comment by vtlkvl** [comment]
It should be resolved in Kong PDK 0.35.

**Comment by mdrizwan-byte** [comment]
@fffonion when is 0.6.0 going to release, looks like the memory leak isssue isn't fixed in PDK 0.35
